language: php

php:
  7.4.7

install:
  composer install

services:
  - mysql

cache:
  - vendor

before_script:
  - cp .env.travis .env
  - sudo mysql -e 'CREATE DATABASE `testing`;'
  - sudo mysql -e 'CREATE DATABASE `tdd`;'
  - composer install

script:
  - php artisan key:generate --force
  - php artisan migrate:refresh --force
  - composer phpcs
  - vendor/bin/phpunit

notifications:
  email:
    recipients:
      - susana.s7@hotmail.com
    on_success: always