language: php

php:
  7.4

install:
  composer install

services:
  - mysql

cache:
  - vendor

before_install:
  - cp .env.testing .env
  - sudo mysql -e 'CREATE DATABASE tdd;'

before_script:
  - composer install
  - php artisan key:generate
  - npm install

script:
  - php artisan optimize
  - php artisan migrate:refresh
  - composer phpcs
  - vendor/bin/phpunit

notifications:
  email:
    recipients:
      - susana.s7@hotmail.com
    on_success: always
    on_failure: always
