language: php

php:
  7.4.7

install:
  composer install

services:
  - mysql

deploy:
  github-token: $GITHUB_TOKEN

before_script:
  - cp .env.travis .env
  - sudo mysql -e 'CREATE DATABASE `travis`;'
  - composer install
  - php artisan key:generate
  - composer require predis/predis

script:
  - vendor/bin/phpunit

notifications:
  email:
    recipients:
      - susana.s7@hotmail.com
    on_success: always
    on_failure: always
