language: php

php:
  7.4.3

install:
  composer install

services:
  - mysql

dist: 
  - precise

cache:
  - vendor

before_install:
    - sudo mysql -e 'CREATE DATABASE testing;'

before_script:
  - cp .env.travis .env
  - composer install
  - php artisan key:generate

script:
  - php artisan optimize
  - php artisan migrate:refresh
  - composer phpcs
  - vendor/bin/phpunit

notifications:
  email:
    recipients:
      - susana.s7@hotmail.com
    on_success: always
    on_failure: always
