language: php

php:
  7.4.7

install:
  composer install

services:
  - mysql

cache:
  - vendor

deploy:
  provider: heroku
  keep-history: true
  api_key: e26df04c-2d59-42f4-9f45-744c202f12bd
  app: mercatodo
  on:
    repo: susanas7/MERCATODO.
  github-token: $GITHUB_TOKEN

before_script:
  - cp .env.travis .env
  - sudo mysql -e 'CREATE DATABASE `testing`;'
  - composer install
  - php artisan key:generate

script:
  - php artisan optimize
  - php artisan migrate:refresh
  - composer phpcs
  - vendor/bin/phpunit

notifications:
  email:
    recipients:
      - susana.s7@hotmail.com
    on_success: always
    on_failure: always
