language: php

php:
  7.4.7

services:
  -mysql

git:
  depth: 3

install:
  composer install

deploy:
  github-token: $GITHUB_TOKEN

before script:
  -cp .env.testing.example .env.testing
  -composer self-update

script:
  -vendor/bin/phpunit
