language: php

php:
  7.4.7

install:
  composer install

deploy:
  github-token: $GITHUB_TOKEN

before_script:
  - cp .env.example .env
  - composer install
  - php artisan key:generate
  - php artisan jwt:secret

script:
  -vendor/bin/phpunit
